import { useEffect, useRef } from 'react';
import { AlertTriangle, Database, Info, ShieldAlert, X, Wind, Waves, CloudRain, UsersRound, Shield } from 'lucide-react';
import type { ScenarioCalculationInputs, ScenarioCalculationOutputs } from '../data/calculations';
import { formatPopulation } from '../data/calculations';
import { zones } from '../data/scenario';

type Props = {
  inputs: ScenarioCalculationInputs;
  outputs: ScenarioCalculationOutputs;
  onClose: () => void;
};

const fmt = (value: number, digits = 2) => value.toFixed(digits);

export default function CalculationsDialog({ inputs, outputs, onClose }: Props) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);
  const selected = zones.find((zone) => zone.id === inputs.selectedZone) ?? zones[0];

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (!dialog.open) dialog.showModal();
    closeRef.current?.focus();
    return () => {
      if (dialog.open) dialog.close();
    };
  }, []);

  return (
    <dialog
      ref={dialogRef}
      className="calculation-dialog"
      aria-labelledby="calculation-dialog-title"
      onCancel={(event) => { event.preventDefault(); onClose(); }}
      onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}
    >
      <div className="calculation-dialog-inner">
        <header className="calculation-dialog-head">
          <div>
            <p className="section-kicker">DATA SOURCES / METHOD / LIMITS</p>
            <h2 id="calculation-dialog-title">What IRIS is showing — and what it isn't.</h2>
            <p>Current inputs: <b>IMD {outputs.imdCategory} (Level {inputs.intensity})</b> · {selected.name}, {selected.state} · {inputs.tide} · {inputs.seaLevel}</p>
          </div>
          <button ref={closeRef} className="calculation-close" type="button" aria-label="Close data and calculations" onClick={onClose}><X size={20}/></button>
        </header>

        <div className="data-integrity-banner" role="note">
          <ShieldAlert size={21}/>
          <div><b>Planning scenario — not for real-world emergency decisions.</b><span>Figures are illustrative estimates based on IMD climatological relationships. No live forecast model, real-time satellite feed, or validated hydrodynamic surge simulation is connected. Always consult IMD imd.gov.in, NDMA ndma.gov.in, and your District Disaster Management Authority for official guidance.</span></div>
        </div>

        <section className="data-facts-grid" aria-label="Data provenance and reliability">
          <article className="data-fact-card"><span className="data-fact-icon"><Database size={19}/></span><h3>Data sources</h3><p><b>Population:</b> Census 2011, coastal district/mandal aggregates (SRIS coastal layer). <b>Cyclone shelters:</b> NDMA Cyclone Shelter Programme 2022 report. <b>Historical events:</b> IMD Best Track Archive (Bay of Bengal). <b>Vulnerability indices:</b> IMD/NDMA guidance + IPCC AR6 coastal risk framework.</p></article>
          <article className="data-fact-card"><span className="data-fact-icon"><Info size={19}/></span><h3>Surge formula basis</h3><p>IMD Storm Surge Atlas (INCOIS/NIOT 2020); NIOT hindcast studies for Fani 2019 (~4.8 m at Puri) and Amphan 2020 (~5.1 m at Sagar Island). Zone geometry modifiers applied for delta/estuary amplification. Tide: typical meso-tidal BoB spring range ~0.5–0.8 m.</p></article>
          <article className="data-fact-card"><span className="data-fact-icon"><AlertTriangle size={19}/></span><h3>Reliability limits</h3><p>Surge values are median estimates for the IMD category — actual impact depends on track angle, coastal bathymetry, drainage, and local elevation (none modelled here). Rainfall is BoB cyclone climatology; actual accumulations vary widely. Population exposure is a rough fraction, not a headcount.</p></article>
          <article className="data-fact-card"><span className="data-fact-icon"><Info size={19}/></span><h3>AI advisory</h3><p>Advisories are generated by Gemini 1.5 Flash using scenario parameters. They are planning concept drafts only — not reviewed by meteorologists or government authorities. Multilingual support covers 6 Indian languages (English, Hindi, Telugu, Bengali, Tamil, Gujarati).</p></article>
        </section>

        <section className="calculation-section" aria-labelledby="formula-title">
          <div className="calculation-section-head"><div><p className="section-kicker">LIVE FROM CURRENT INPUTS · IMD-REFERENCED</p><h3 id="formula-title">The arithmetic behind the cards</h3></div><span className="demo-state-pill">ILLUSTRATIVE ESTIMATES</span></div>
          <div className="formula-grid">
            <article className="formula-card">
              <div className="formula-card-top"><h4><Waves size={14}/> Storm surge planning band</h4><b>{fmt(outputs.surgeMeters, 1)} m</b></div>
              <code>Base({outputs.imdCategory}) {fmt(outputs.surgeMeters - outputs.tideFactor - outputs.seaLevelFactor, 2)}m + tide {fmt(outputs.tideFactor, 2)}m + SLR {fmt(outputs.seaLevelFactor, 2)}m = {fmt(outputs.surgeMeters, 1)} m</code>
              <p>Surge base values from IMD Storm Surge Atlas category medians. {selected.name} zone geometry modifier applied. Tide factor: meso-tidal BoB spring/mean difference. Sea-level rise: IPCC AR6 RCP4.5 mid-century median.</p>
            </article>
            <article className="formula-card">
              <div className="formula-card-top"><h4><Wind size={14}/> Wind speed estimate</h4><b>{outputs.windSpeedKmh} km/h</b></div>
              <code>IMD {outputs.imdCategory} central estimate: {outputs.windSpeedKmh} km/h sustained</code>
              <p>Representative central value for IMD category band. Reference: Saffir-Simpson / IMD wind-category classification. Actual wind speeds at landfall depend on track, intensification, and local orography.</p>
            </article>
            <article className="formula-card">
              <div className="formula-card-top"><h4><UsersRound size={14}/> Regional exposure estimate</h4><b>{formatPopulation(outputs.regionalExposureEstimate)}</b></div>
              <code>District pop. {formatPopulation(selected.population)} (Census 2011) × exposure fraction {Math.round((outputs.regionalExposureEstimate / selected.population) * 100)}% = {formatPopulation(outputs.regionalExposureEstimate)}</code>
              <p>Exposure fraction scales linearly with surge height (8–65% range). Population base from Census 2011 coastal mandal/taluka aggregates. Not a real-time headcount.</p>
            </article>
            <article className="formula-card">
              <div className="formula-card-top"><h4><CloudRain size={14}/> 24-hour rainfall</h4><b>{outputs.rainfall24hMm} mm</b></div>
              <code>IMD BoB climatology base({inputs.intensity}) + zone modifier = {outputs.rainfall24hMm} mm</code>
              <p>Based on IMD Extended Period/Bay of Bengal cyclone rainfall climatology tables. Sundarbans/Krishna delta modifiers applied for known rainfall enhancement. Actual accumulations highly variable.</p>
            </article>
            <article className="formula-card">
              <div className="formula-card-top"><h4><Shield size={14}/> Potential liquidity (₹ crore)</h4><b>₹{fmt(outputs.estimatedLiquidityCrore, 1)} Cr</b></div>
              <code>Base + surge×6.5 + rainfall×0.04 + exposure factor = ₹{fmt(outputs.estimatedLiquidityCrore, 1)} Cr</code>
              <p>Illustrative scaling for parametric coverage discussion. Not a quote, contract, or actuarially validated figure. Reference: NDMA parametric insurance feasibility study 2021.</p>
            </article>
            <article className="formula-card">
              <div className="formula-card-top"><h4>Scenario severity index</h4><b>{outputs.scenarioIndex} / 100</b></div>
              <code>Composite: surge weight + rainfall weight + tide/SLR bonus + zone bonus = {outputs.scenarioIndex}</code>
              <p>Planning heuristic combining surge, rainfall, tide, sea-level rise, and zone geometry. Not a validated probability or model confidence score.</p>
            </article>
          </div>
        </section>

        <section className="outputs-note" aria-label="Dashboard output summary">
          <b>Key data citations</b>
          <p>IMD Storm Surge Atlas (INCOIS/NIOT, 2020) · NIOT Fani &amp; Amphan surge hindcasts · Census of India 2011 (coastal districts) · NDMA Cyclone Shelter Programme 2022 · IPCC AR6 WG2 Chapter 15 (Coastal Systems) · IMD Best Track Archive (Bay of Bengal) · NDMA Post-Cyclone Damage Reports (2013–2023)</p>
        </section>

        <footer className="calculation-dialog-foot"><span><Info size={15}/>Use official IMD (imd.gov.in), NDMA (ndma.gov.in), and DDMA advisories for real-world decisions.</span><button className="button-primary" type="button" onClick={onClose}>Back to the dashboard</button></footer>
      </div>
    </dialog>
  );
}
